fixtures:
  repositories:
    archive: "git://github.com/voxpupuli/puppet-archive.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    ssh: "git://github.com/saz/puppet-ssh.git"
    apt: "git://github.com/puppetlabs/puppetlabs-apt.git"
